name: Sync Subscribers

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  update-subscribers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gspread oauth2client

      - name: Create service_account.json
        run: echo "${{ secrets.GOOGLE_SERVICE_KEY }}" > service_account.json

      - name: Run sync script
        run: python sync_subscribers.py

      - name: Commit and push updated subscribers.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add subscribers.json
          git commit -m "🤖 Update subscribers list"
          git push
